ngnix:
  restart: always
  build: ./ngnix
  volumes:
    - ./app/static:/var/www/tnt-backend/app/static
  links:
    - app
  ports:
    - "80:80"

app:
  restart: always
  build: ./app
  ports:
    - "8080"
  links:
    - mongo
  volumes:
    - ./app:/app
    - ../log:/tmp/log
  dockerfile: Dockerfile


mongo:
  restart: always
  image: mongo:3.3.8
  ports:
    - "27017:27017"
  volumes:
    - ../mongo:/data/db

