version: '2'
services:
  ngnix:
    restart: always
    build: ./ngnix
    volumes:
      - ./app/static:/var/www/tnt-backend/app/static
    links:
      - app
    ports:
      - "80:80"
  app:
    restart: always
    build:
      context: ./app
      dockerfile: /DockerFiles/prod/Dockerfile
    ports:
      - "3000:80"
    links:
      - mongo
    volumes:
      - ./app:/app
      - ./tnt/logs/app:/tmp/log

  mongo:
    restart: always
    image: mongo:3.3.15
    ports:
      - "27017:27017"
    volumes:
      - ./tnt/logs/app-db:/data/db
